version: "2"
services:
  # app:
  #   build: .
  #   networks:
  #     - my_app
  #   volumes:
  #     - .:/data
  #   ports:
  #     - "5000:5000"
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks: 
      - my_app
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - my_app
  # mysql:
  #   image: mysql
  #   ports:
  #     - "3306:3306"
  #   networks:
  #     - my_app
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: 123456
networks:
  my_app: